OPENAI_API_KEY = "sk-proj-PgVhSRnSntedFb58x7TtT3BlbkFJ69zmrUsy97HuzLj8g2RO"
TOGETHERAI_API_KEY="3d186a22e21216780ccc2c3a1cb40227a1a929562086fd19bd745b0f892a240e"
TOGETHERAI_BASE_URL="https://api.together.xyz"
ANYSCALE_API_KEY="esecret_whquvyf44i14kqf4em3bz265v3"
ANYSCALE_BASE_URL="https://api.endpoints.anyscale.com/v1"